const $=s=>document.querySelector(s);let records=[];
async function api(path,opt={}){const r=await fetch(path,{headers:{'Content-Type':'application/json'},...opt});if(!r.ok){const x=await r.json().catch(()=>({}));throw new Error(x.error||'Não foi possível concluir a operação.')}return r.status===204?null:r.json()}
function object(form){return Object.fromEntries(new FormData(form));}
async function refresh(){const [me,cfg,data]=await Promise.all([api('/api/auth/me'),api('/api/config'),api('/api/emendas')]);cfg.municipios.forEach(x=>$('#municipio').insertAdjacentHTML('beforeend',`<option>${x}</option>`));if(!me.authenticated)return;$('#loginPanel').hidden=true;$('#adminPanel').hidden=false;$('#adminEmail').textContent=me.email;records=data.items;$('#records').innerHTML=records.map(x=>`<article><strong>${x.numeroEmenda}</strong><span>${x.municipio} · ${x.deputado}</span><button data-delete="${x.id}" class="danger">Excluir</button></article>`).join('')||'<p class="text-muted">Nenhum registro.</p>';document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=async()=>{if(confirm('Excluir este registro?')){await api('/api/admin/emendas/'+encodeURIComponent(b.dataset.delete),{method:'DELETE'});location.reload()}})}
$('#loginForm').onsubmit=async e=>{e.preventDefault();try{await api('/api/auth/login',{method:'POST',body:JSON.stringify(object(e.target))});location.reload()}catch(x){$('#loginError').textContent=x.message}};
$('#logout').onclick=async()=>{await api('/api/auth/logout',{method:'POST'});location.reload()};
$('#emendaForm').onsubmit=async e=>{e.preventDefault();try{const p=object(e.target);p.ano=+p.ano;p.valorEmpenhado=+p.valorEmpenhado;p.valorPago=+p.valorPago;await api('/api/admin/emendas',{method:'POST',body:JSON.stringify(p)});$('#formMessage').textContent='Emenda salva.';e.target.reset();setTimeout(()=>location.reload(),500)}catch(x){$('#formMessage').textContent=x.message}};
$('#syncForm').onsubmit=async e=>{e.preventDefault();try{const anos=object(e.target).anos.split(',').map(x=>+x.trim()).filter(Boolean);const x=await api('/api/admin/sincronizar',{method:'POST',body:JSON.stringify({anos})});$('#syncMessage').textContent=`${x.importadas} registro(s) importado(s).`;setTimeout(()=>location.reload(),700)}catch(x){$('#syncMessage').textContent=x.message}};
refresh().catch(console.error);
