services:
  - type: web
    name: observatorio-emendas-baixada-santista
    runtime: node
    plan: free
    branch: arena/019fdec0-paginateste
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: ADMIN_EMAIL
        value: admin@seu-dominio.org.br
      - key: ADMIN_PASSWORD
        generateValue: true
      - key: CGU_API_KEY
        sync: false
