const areaConfig={saude:{label:'Saúde',icon:'🏥'},educacao:{label:'Educação',icon:'📚'},infraestrutura:{label:'Infraestrutura',icon:'🏗️'},cultura:{label:'Cultura',icon:'🎭'},outros:{label:'Outros',icon:'📌'}};
const statusLabels={'em-execucao':'Em Execução',concluido:'Concluído',planejamento:'Planejamento'};
let emendasData=[], filteredEmendas=[], currentFilter='all', searchTerm='';
const money=v=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0}).format(v||0);
const text=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function request(path){const r=await fetch(path);if(!r.ok)throw new Error('Não foi possível carregar os dados.');return r.json()}
async function load(){try{const [config,data,stats]=await Promise.all([request('/api/config'),request('/api/emendas'),request('/api/estatisticas')]);emendasData=data.items;filteredEmendas=[...emendasData];fillOptions(config.municipios);updateKPIs(stats);renderCharts();renderTable();document.getElementById('lastUpdate').textContent=stats.ultimaAtualizacao?`Atualizado em ${new Date(stats.ultimaAtualizacao).toLocaleString('pt-BR')}`:'Sem sincronização oficial';}catch(e){document.getElementById('lastUpdate').textContent=e.message;}}
function fillOptions(municipios){const m=document.getElementById('municipioSelect'),a=document.getElementById('anoSelect'); municipios.forEach(x=>m.insertAdjacentHTML('beforeend',`<option>${text(x)}</option>`)); [...new Set(emendasData.map(x=>x.ano))].sort((x,y)=>y-x).forEach(x=>a.insertAdjacentHTML('beforeend',`<option>${x}</option>`));}
function filters(){const municipio=document.getElementById('municipioSelect').value,ano=document.getElementById('anoSelect').value;filteredEmendas=emendasData.filter(e=>(currentFilter==='all'||e.area===currentFilter)&&(!municipio||e.municipio===municipio)&&(!ano||String(e.ano)===ano)&&(!searchTerm||Object.values(e).join(' ').toLowerCase().includes(searchTerm)));renderTable();}
function updateKPIs(s){document.getElementById('totalEmendas').textContent=s.totalEmendas;document.getElementById('totalDeputados').textContent=s.totalDeputados;document.getElementById('totalValor').textContent=money(s.valorEmpenhado);document.getElementById('totalExecucao').textContent=s.emExecucao;}
function chart(target,groups,label){const entries=Object.entries(groups).sort((a,b)=>b[1]-a[1]),max=Math.max(...entries.map(x=>x[1]),1);document.getElementById(target).innerHTML=entries.map(([n,v])=>`<div class="chart-bar"><div class="chart-bar-label"><span class="chart-bar-name">${label(n)}</span><span class="chart-bar-value">${money(v)}</span></div><div class="chart-bar-track"><div class="chart-bar-fill" style="width:${v/max*100}%"></div></div></div>`).join('')||'<p class="text-muted">Sem dados para os filtros selecionados.</p>'}
function renderCharts(){const dep={},area={};emendasData.forEach(e=>{dep[e.deputado]=(dep[e.deputado]||0)+(e.valorEmpenhado||e.valor||0);area[e.area]=(area[e.area]||0)+(e.valorEmpenhado||e.valor||0)});chart('deputadoChart',dep,x=>text(x));chart('areaChart',area,x=>`${areaConfig[x]?.icon||'📌'} ${areaConfig[x]?.label||text(x)}`)}
function renderTable(){const body=document.getElementById('tableBody'),empty=document.getElementById('emptyState');document.getElementById('recordCount').textContent=`${filteredEmendas.length} registros`;empty.style.display=filteredEmendas.length?'none':'block';body.innerHTML=filteredEmendas.map(e=>`<tr class="table-row-clickable" data-id="${text(e.id)}"><td><div class="table-numero">${text(e.numeroEmenda)}</div></td><td><div class="table-deputado">${text(e.deputado)}</div><small>${text(e.municipio)}</small></td><td>${text(e.partido)}</td><td><div class="table-projeto">${text(e.projeto)}</div></td><td>${areaConfig[e.area]?.icon||'📌'} ${areaConfig[e.area]?.label||text(e.area)}</td><td class="table-valor">${money(e.valorEmpenhado||e.valor)}</td><td>${text(e.ano)}</td><td><span class="table-status status-${text(e.status)}">${statusLabels[e.status]||text(e.status)}</span></td></tr>`).join('');document.querySelectorAll('.table-row-clickable').forEach(row=>row.onclick=()=>openModal(row.dataset.id));}
function openModal(id){const e=emendasData.find(x=>String(x.id)===String(id));if(!e)return;const set=(id,v)=>document.getElementById(id).textContent=v;set('modalNumero',e.numeroEmenda);set('modalDeputado',e.deputado);set('modalPartido',e.partido);set('modalArea',`${areaConfig[e.area]?.icon||'📌'} ${areaConfig[e.area]?.label||e.area}`);document.getElementById('modalStatus').innerHTML=`<span class="table-status status-${text(e.status)}">${statusLabels[e.status]||text(e.status)}</span>`;set('modalValor',money(e.valorEmpenhado||e.valor));set('modalAno',e.ano);set('modalDataAprovacao',e.dataAprovacao||'Não informado');set('modalProjeto',e.projeto);set('modalDescricao',e.descricaoCompleta);set('modalBeneficiarios',e.beneficiarios);document.getElementById('modalOverlay').style.display='flex';document.body.style.overflow='hidden';}
function closeModal(){document.getElementById('modalOverlay').style.display='none';document.body.style.overflow=''}
document.addEventListener('DOMContentLoaded',()=>{document.querySelectorAll('.chip').forEach(b=>b.onclick=()=>{document.querySelectorAll('.chip').forEach(x=>x.classList.remove('active'));b.classList.add('active');currentFilter=b.dataset.filter;filters()});document.getElementById('searchInput').oninput=e=>{searchTerm=e.target.value.toLowerCase();filters()};['municipioSelect','anoSelect'].forEach(id=>document.getElementById(id).onchange=filters);document.getElementById('modalClose').onclick=closeModal;document.getElementById('modalOverlay').onclick=e=>{if(e.target.id==='modalOverlay')closeModal()};document.onkeydown=e=>{if(e.key==='Escape')closeModal()};load()});
